import type { FoodItem, MealWindow } from './fitnessMealPlanner';

export type FoodCategory = 'protein' | 'carb' | 'fat' | 'vegetable' | 'snack';

export interface CatalogFoodItem extends FoodItem {
  category: FoodCategory;
  mealWindows: MealWindow[];
}

export const FOOD_CATALOG: CatalogFoodItem[] = [
  // ---- Protein ----
  {
    id: 'egg-whites',
    barcode: '0001112223334',
    name: 'Egg Whites (Scrambled)',
    category: 'protein',
    portionRaw: '150g (raw liquid)',
    caloriesRaw: 78,
    portionCooked: '120g (cooked)',
    caloriesCooked: 90,
    proteinGrams: 16,
    carbGrams: 2,
    fatGrams: 0.5,
    snackProfile: ['high_protein'],
    estimatedPrices: { walmart: 2.5, foodLion: 2.8, aldi: 2.2, kroger: 2.7 },
    mealWindows: ['breakfast'],
  },
  {
    id: 'grilled-chicken',
    barcode: '0003334445556',
    name: 'Grilled Chicken Breast',
    category: 'protein',
    portionRaw: '170g (raw)',
    caloriesRaw: 187,
    portionCooked: '130g (cooked)',
    caloriesCooked: 215,
    proteinGrams: 39,
    carbGrams: 0,
    fatGrams: 5,
    snackProfile: ['high_protein', 'savory'],
    estimatedPrices: { walmart: 3.5, foodLion: 3.9, aldi: 3.2, kroger: 3.7 },
    mealWindows: ['lunch', 'dinner'],
  },
  {
    id: 'salmon',
    barcode: '0005556667778',
    name: 'Baked Salmon Fillet',
    category: 'protein',
    portionRaw: '160g (raw)',
    caloriesRaw: 233,
    portionCooked: '125g (cooked)',
    caloriesCooked: 260,
    proteinGrams: 34,
    carbGrams: 0,
    fatGrams: 13,
    snackProfile: ['savory', 'high_protein'],
    estimatedPrices: { walmart: 6.5, foodLion: 7.2, aldi: 5.9, kroger: 6.8 },
    mealWindows: ['dinner'],
  },
  {
    id: 'turkey-breast',
    barcode: '0001122334455',
    name: 'Roasted Turkey Breast',
    category: 'protein',
    portionRaw: '170g (raw)',
    caloriesRaw: 180,
    portionCooked: '135g (cooked)',
    caloriesCooked: 200,
    proteinGrams: 36,
    carbGrams: 0,
    fatGrams: 3,
    snackProfile: ['high_protein', 'savory'],
    estimatedPrices: { walmart: 3.9, foodLion: 4.3, aldi: 3.6, kroger: 4.1 },
    mealWindows: ['lunch', 'dinner'],
  },
  {
    id: 'tofu',
    barcode: '0002233445566',
    name: 'Firm Tofu Cubes',
    category: 'protein',
    portionRaw: '150g (raw)',
    caloriesRaw: 120,
    portionCooked: '140g (cooked)',
    caloriesCooked: 135,
    proteinGrams: 14,
    carbGrams: 3,
    fatGrams: 7,
    snackProfile: ['high_protein', 'savory'],
    estimatedPrices: { walmart: 1.8, foodLion: 2.0, aldi: 1.6, kroger: 1.9 },
    mealWindows: ['lunch', 'dinner'],
  },
  // ---- Carb ----
  {
    id: 'oatmeal',
    barcode: '0002223334445',
    name: 'Oatmeal with Berries',
    category: 'carb',
    portionRaw: '50g (dry oats)',
    caloriesRaw: 190,
    portionCooked: '220g (cooked)',
    caloriesCooked: 180,
    proteinGrams: 7,
    carbGrams: 34,
    fatGrams: 3,
    snackProfile: ['sweet'],
    estimatedPrices: { walmart: 1.2, foodLion: 1.4, aldi: 1.0, kroger: 1.3 },
    mealWindows: ['breakfast'],
  },
  {
    id: 'brown-rice',
    barcode: '0004445556667',
    name: 'Brown Rice',
    category: 'carb',
    portionRaw: '90g (raw)',
    caloriesRaw: 325,
    portionCooked: '195g (cooked)',
    caloriesCooked: 215,
    proteinGrams: 5,
    carbGrams: 45,
    fatGrams: 1.8,
    snackProfile: ['savory'],
    estimatedPrices: { walmart: 0.9, foodLion: 1.0, aldi: 0.7, kroger: 0.95 },
    mealWindows: ['lunch', 'dinner'],
  },
  {
    id: 'sweet-potato',
    barcode: '0003344556677',
    name: 'Roasted Sweet Potato',
    category: 'carb',
    portionRaw: '200g (raw)',
    caloriesRaw: 172,
    portionCooked: '160g (cooked)',
    caloriesCooked: 150,
    proteinGrams: 3,
    carbGrams: 35,
    fatGrams: 0.2,
    snackProfile: ['sweet', 'savory'],
    estimatedPrices: { walmart: 1.0, foodLion: 1.1, aldi: 0.85, kroger: 1.05 },
    mealWindows: ['lunch', 'dinner'],
  },
  {
    id: 'whole-wheat-bread',
    barcode: '0004455667788',
    name: 'Whole Wheat Toast',
    category: 'carb',
    portionRaw: '2 slices (70g)',
    caloriesRaw: 170,
    portionCooked: '2 slices, toasted (65g)',
    caloriesCooked: 165,
    proteinGrams: 8,
    carbGrams: 30,
    fatGrams: 2,
    snackProfile: ['savory'],
    estimatedPrices: { walmart: 0.6, foodLion: 0.7, aldi: 0.5, kroger: 0.65 },
    mealWindows: ['breakfast'],
  },
  // ---- Fat ----
  {
    id: 'almonds',
    barcode: '0005566778899',
    name: 'Raw Almonds',
    category: 'fat',
    portionRaw: '28g',
    caloriesRaw: 164,
    portionCooked: '28g (roasted)',
    caloriesCooked: 170,
    proteinGrams: 6,
    carbGrams: 6,
    fatGrams: 14,
    snackProfile: ['crunchy', 'salty', 'high_protein'],
    estimatedPrices: { walmart: 1.3, foodLion: 1.5, aldi: 1.1, kroger: 1.4 },
    mealWindows: ['snacks'],
  },
  {
    id: 'avocado',
    barcode: '0006677889900',
    name: 'Avocado (Half)',
    category: 'fat',
    portionRaw: '100g (raw)',
    caloriesRaw: 160,
    portionCooked: '95g (grilled)',
    caloriesCooked: 155,
    proteinGrams: 2,
    carbGrams: 9,
    fatGrams: 15,
    snackProfile: ['savory'],
    estimatedPrices: { walmart: 0.9, foodLion: 1.0, aldi: 0.75, kroger: 0.95 },
    mealWindows: ['lunch', 'dinner'],
  },
  {
    id: 'peanut-butter',
    barcode: '0007788990011',
    name: 'Peanut Butter (2 tbsp)',
    category: 'fat',
    portionRaw: '32g',
    caloriesRaw: 190,
    portionCooked: '32g',
    caloriesCooked: 190,
    proteinGrams: 7,
    carbGrams: 6,
    fatGrams: 16,
    snackProfile: ['sweet', 'savory', 'high_protein'],
    estimatedPrices: { walmart: 1.4, foodLion: 1.6, aldi: 1.2, kroger: 1.5 },
    mealWindows: ['snacks'],
  },
  // ---- Vegetable ----
  {
    id: 'roasted-veggies',
    barcode: '0006667778889',
    name: 'Roasted Mixed Vegetables',
    category: 'vegetable',
    portionRaw: '200g (raw)',
    caloriesRaw: 90,
    portionCooked: '150g (cooked)',
    caloriesCooked: 110,
    proteinGrams: 3,
    carbGrams: 18,
    fatGrams: 2,
    snackProfile: ['savory', 'crunchy'],
    estimatedPrices: { walmart: 1.8, foodLion: 2.0, aldi: 1.6, kroger: 1.9 },
    mealWindows: ['lunch', 'dinner'],
  },
  {
    id: 'broccoli',
    barcode: '0008899001122',
    name: 'Steamed Broccoli',
    category: 'vegetable',
    portionRaw: '180g (raw)',
    caloriesRaw: 61,
    portionCooked: '160g (steamed)',
    caloriesCooked: 55,
    proteinGrams: 4,
    carbGrams: 11,
    fatGrams: 0.6,
    snackProfile: ['savory', 'crunchy'],
    estimatedPrices: { walmart: 1.2, foodLion: 1.3, aldi: 1.0, kroger: 1.25 },
    mealWindows: ['lunch', 'dinner'],
  },
  {
    id: 'spinach-salad',
    barcode: '0009900112233',
    name: 'Spinach Salad Mix',
    category: 'vegetable',
    portionRaw: '85g (raw)',
    caloriesRaw: 20,
    portionCooked: '75g (sauteed)',
    caloriesCooked: 35,
    proteinGrams: 2,
    carbGrams: 3,
    fatGrams: 0.3,
    snackProfile: ['savory'],
    estimatedPrices: { walmart: 2.0, foodLion: 2.2, aldi: 1.8, kroger: 2.1 },
    mealWindows: ['lunch', 'dinner'],
  },
  // ---- Snack ----
  {
    id: 'pretzels',
    barcode: '0007778889990',
    name: 'Mini Pretzels',
    category: 'snack',
    portionRaw: '30g',
    caloriesRaw: 110,
    portionCooked: '30g',
    caloriesCooked: 110,
    proteinGrams: 3,
    carbGrams: 23,
    fatGrams: 1,
    snackProfile: ['salty', 'crunchy'],
    estimatedPrices: { walmart: 0.6, foodLion: 0.7, aldi: 0.5, kroger: 0.65 },
    mealWindows: ['snacks'],
  },
  {
    id: 'greek-yogurt',
    barcode: '0008889990001',
    name: 'Greek Yogurt Cup',
    category: 'snack',
    portionRaw: '170g',
    caloriesRaw: 100,
    portionCooked: '170g',
    caloriesCooked: 100,
    proteinGrams: 17,
    carbGrams: 6,
    fatGrams: 0,
    snackProfile: ['high_protein', 'sweet'],
    estimatedPrices: { walmart: 1.1, foodLion: 1.3, aldi: 0.9, kroger: 1.2 },
    mealWindows: ['snacks'],
  },
  {
    id: 'trail-mix',
    barcode: '0009990001112',
    name: 'Trail Mix',
    category: 'snack',
    portionRaw: '40g',
    caloriesRaw: 190,
    portionCooked: '40g',
    caloriesCooked: 190,
    proteinGrams: 5,
    carbGrams: 17,
    fatGrams: 12,
    snackProfile: ['sweet', 'crunchy', 'savory'],
    estimatedPrices: { walmart: 1.5, foodLion: 1.7, aldi: 1.3, kroger: 1.6 },
    mealWindows: ['snacks'],
  },
  {
    id: 'jerky',
    barcode: '0000112223335',
    name: 'Beef Jerky',
    category: 'snack',
    portionRaw: '28g',
    caloriesRaw: 80,
    portionCooked: '28g',
    caloriesCooked: 80,
    proteinGrams: 11,
    carbGrams: 3,
    fatGrams: 1.5,
    snackProfile: ['salty', 'savory', 'high_protein'],
    estimatedPrices: { walmart: 1.9, foodLion: 2.2, aldi: 1.7, kroger: 2.1 },
    mealWindows: ['snacks'],
  },
  {
    id: 'rice-cakes',
    barcode: '0001223344556',
    name: 'Salted Rice Cakes',
    category: 'snack',
    portionRaw: '2 cakes (18g)',
    caloriesRaw: 70,
    portionCooked: '2 cakes (18g)',
    caloriesCooked: 70,
    proteinGrams: 1,
    carbGrams: 15,
    fatGrams: 0.5,
    snackProfile: ['salty', 'crunchy'],
    estimatedPrices: { walmart: 0.5, foodLion: 0.6, aldi: 0.4, kroger: 0.55 },
    mealWindows: ['snacks'],
  },
];
